"""Inventory classification rules for code-wiki."""

SKIP_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".cache",
    ".next",
    ".nuxt",
    ".turbo",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "build",
    "code-wiki",
    "coverage",
    "dist",
    "node_modules",
    "target",
    "vendor",
}

MANIFEST_NAMES = {
    "AGENTS.md",
    "BUILD",
    "BUILD.bazel",
    "Cargo.toml",
    "CMakeLists.txt",
    "Gemfile",
    "Makefile.am",
    "Makefile.in",
    "Package.swift",
    "Podfile",
    "README.md",
    "WORKSPACE",
    "WORKSPACE.bazel",
    "bun.lockb",
    "composer.json",
    "configure",
    "configure.ac",
    "deno.json",
    "docker-compose.yml",
    "go.mod",
    "gradle.properties",
    "package-lock.json",
    "package.json",
    "pnpm-lock.yaml",
    "pyproject.toml",
    "requirements.txt",
    "setup.cfg",
    "setup.py",
    "meson.build",
    "meson_options.txt",
    "tsconfig.json",
    "uv.lock",
    "yarn.lock",
}

DOC_NAMES = {
    "AGENTS.md",
    "CHANGELOG.md",
    "COPYING",
    "CONTRIBUTING.md",
    "LICENSE",
    "LICENSE.md",
    "LICENSE.txt",
    "NOTICE",
    "NOTICE.md",
    "NOTICE.txt",
    "README.md",
    "SECURITY.md",
}

SOURCE_DIR_NAMES = {
    "app",
    "apps",
    "cmd",
    "components",
    "internal",
    "lib",
    "packages",
    "pkg",
    "server",
    "source",
    "src",
    "sources",
}

TEST_DIR_NAMES = {
    "__tests__",
    "features",
    "spec",
    "specs",
    "test",
    "tests",
}

INTERFACE_DIR_NAMES = {
    "api",
    "apis",
    "header",
    "headers",
    "include",
    "includes",
    "public",
}

ENTRYPOINT_NAMES = {
    "app.go",
    "app.py",
    "app.ts",
    "app.tsx",
    "cli.py",
    "index.js",
    "index.ts",
    "index.tsx",
    "main.go",
    "main.py",
    "main.rs",
    "main.swift",
    "main.ts",
    "main.tsx",
    "server.js",
    "server.py",
    "server.ts",
}

NOISY_SOURCE_PARTS = {
    ".github",
    "__tests__",
    "bench",
    "benches",
    "benchmark",
    "benchmarks",
    "benchsuite",
    "deps",
    "dist",
    "docs",
    "documentation",
    "example",
    "examples",
    "fixture",
    "fixtures",
    "playground",
    "playgrounds",
    "sample",
    "samples",
    "spec",
    "specs",
    "template",
    "templates",
    "testdata",
    "tests",
    "vendor",
}

VENDORED_ROOT_PARTS = {
    "deps",
    "third_party",
    "vendor",
}

OPS_ROOT_PARTS = {
    ".buildkite",
    ".circleci",
    ".github",
    ".gitlab",
    ".gitlab-ci.yml",
    ".readthedocs.yaml",
    "ci",
}

GENERATED_DOC_PARTS = {
    "classes",
    "docsets",
    "enums",
    "extensions",
    "protocols",
    "structs",
}

CODE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".m",
    ".mm",
    ".php",
    ".py",
    ".rb",
    ".rs",
    ".swift",
    ".ts",
    ".tsx",
    ".vue",
}

INTERFACE_EXTENSIONS = {
    ".h",
    ".hh",
    ".hpp",
    ".hxx",
    ".idl",
    ".modulemap",
}

EXT_LANGUAGE = {
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cs": "C#",
    ".css": "CSS",
    ".go": "Go",
    ".h": "C/C++ Header",
    ".hpp": "C++ Header",
    ".html": "HTML",
    ".java": "Java",
    ".js": "JavaScript",
    ".json": "JSON",
    ".jsx": "JavaScript React",
    ".kt": "Kotlin",
    ".m": "Objective-C",
    ".md": "Markdown",
    ".mm": "Objective-C++",
    ".php": "PHP",
    ".py": "Python",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".sh": "Shell",
    ".sql": "SQL",
    ".swift": "Swift",
    ".toml": "TOML",
    ".ts": "TypeScript",
    ".tsx": "TypeScript React",
    ".vue": "Vue",
    ".xml": "XML",
    ".yaml": "YAML",
    ".yml": "YAML",
}

GOVERNANCE_DOC_NAMES = {
    "authors",
    "changelog",
    "codeowners",
    "contributing",
    "copying",
    "license",
    "licence",
    "maintainers",
    "notice",
    "releases",
    "security",
    "support",
}

